# Perfil LOCAL (PC do Fábio)
server.port=8081

# Banco PostgreSQL (Docker local)
spring.datasource.url=jdbc:postgresql://localhost:5434/condominium
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate (Habilita logs e atualizações automáticas)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# CORS (Permite que o frontend de teste se conecte ao backend)
app.cors.allowed-origins=http://localhost:3000,http://localhost:3001
