# Perfil LOCAL (PC do Fábio)
server.port=8081

# Banco PostgreSQL (Docker local)
spring.datasource.url=jdbc:postgresql://localhost:5434/condominium
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate (Habilita logs e atualizações automáticas)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# CORS (Permite que o frontend de teste se conecte ao backend)
app.cors.allowed-origins=http://localhost:3000,http://localhost:3001

# JWT (local)
JWT_SECRET=condominiumSecretKey2026SuperSeguroNaoCompartilhe123456789

# E-mail (local)
MAIL_USER=residencial.oceano.1481@gmail.com
MAIL_PASSWORD=okbk cdzj aitx svqb

# Usuário mestre (DataLoader)
app.master.email=residencial.oceano.1481@gmail.com
app.master.senha=148106
